type_traits depends on config.hpp
When using type_traits headers I get the error below.
Adding "@boost//:config" in my BUILD deps fixes the issue, but type_traits should really include it.

In file included from external/boost/boost/type_traits/is_base_of.hpp:12:
In file included from external/boost/boost/type_traits/is_base_and_derived.hpp:12:
external/boost/boost/type_traits/intrinsics.hpp:13:10: fatal error: 'boost/config.hpp' file not found
#include <boost/config.hpp>
         ^~~~~~~~~~~~~~~~~~
1 error generated.